name: app-web
region: sfo
static_sites:
  - build_command: npm run build
    catchall_document: index.html
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: intrepion/intrepion-hello-world-web-typescript-angular
    name: web
    routes:
      - path: /
    source_dir: /
